# Generated by Django 5.2.6 on 2025-10-06 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_wastecategory_wasteitem_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='digital_credits',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, help_text='Location in Machakos County', max_length=200),
        ),
        migrations.AddField(
            model_name='wasteitem',
            name='credits_earned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='wasteitem',
            name='waste_type',
            field=models.CharField(choices=[('plastic', 'Plastic'), ('paper', 'Paper/Cardboard'), ('metal', 'Metal'), ('glass', 'Glass'), ('organic', 'Organic/Food Waste'), ('agricultural', 'Agricultural Residues'), ('e-waste', 'E-Waste'), ('textile', 'Textile'), ('other', 'Other')], default='plastic', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('household', 'Household'), ('farmer', 'Farmer'), ('collector', 'Waste Collector (Youth/Women)'), ('recycler', 'Recycler/Processor')], default='household', max_length=20),
        ),
        migrations.AlterField(
            model_name='wasteitem',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('pending', 'Pending Pickup'), ('collected', 'Collected'), ('recycled', 'Recycled')], default='available', max_length=20),
        ),
    ]
